### ISSUE TITLE
Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [dapr/website#71]
This issue is part of a CNCF-wide effort to upgrade project websites to GA4 since **Google has deprecated Universal Analytics** (UA). For more details, see:

- https://github.com/cncf/techdocs/issues/108, including reference to a suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Tasks: stages 1 & 2

- [x] Create a GA4 site tag under the **CNCF projects** account.
  The new GA4 stream measurement ID is: **`G-60C6Q1ETC1`**
- [x] Configure GA4 website ID ([gtag.js]) through [Netlify snippet injection]
- [x] Confirm that the GA4 site tag is receiving events
- [x] Confirm that the UA site tag is still receiving events

Notes:

- Corresponding subdomain issues:
  - blog.dapr.io: https://github.com/dapr/blog/issues/92
  - docs.dapr.io: https://github.com/dapr/docs/issues/2861
- Followup: #72

/cc @caniszczyk @nate-double-u

---

Current website analytics info:

- UA site tags, all registered via `analytics.js`: 
  - `UA-149338238-1`, main site tag
  - `UA-149338238-2`: blog
  - `UA-149338238-3`: docs

[connect]: https://support.google.com/analytics/answer/9973999
[gtag.js]: https://developers.google.com/analytics/devguides/collection/gtagjs
[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by msfussell** [comment]
@chalin - Work with me and @greenie-msft or @nyemade-uversky on this. For the blog site you should have access to all the sources now in the repo. Can you confirm?

**Comment by chalin** [comment]
Thanks @msfussell. I confirm that I have access.

**Comment by chalin** [comment]
Closing once again since the main-site migration is done. Migration for subdomains (blog and docs) is tracked separated. For links to their issues, see the opening comment.

**Comment by chalin** [comment]
FYI, I've created, for illustrative purposes, a custom report that shows only docs.dapr.io page views. This illustrates how we can generate reports for separate subdomains (mimicking the UA property setup that existed before):

> <img width="1880" alt="image" src="https://user-images.githubusercontent.com/4140793/201163322-e34a48c1-9bac-47da-9fb5-56b8e7d0d68e.png">
